{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hs.router",
    "module": "core",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.hs.router",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.0.0.aar",
          "url": "core-1.0.0.aar",
          "size": 87994,
          "sha512": "21b3e4ceafb3ab011d845a1c3e58b9f305e1b99a57700680fe846bd07a37d0daf35a2f725898ddda1d8abe3dd0968fe9e137d3da47449c36e74ea276a6c3712c",
          "sha256": "0cafed641d0ea26dfd04b15cb18a1915f766b3f2cee5e237b0ceda6666a80f9b",
          "sha1": "b8467a58ac3499410c1c473d0d5e71ad5f0ee4de",
          "md5": "896acec733738fc2fdd50effc19f5eb6"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.8.20"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "com.hs.router",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.0.0.aar",
          "url": "core-1.0.0.aar",
          "size": 87994,
          "sha512": "21b3e4ceafb3ab011d845a1c3e58b9f305e1b99a57700680fe846bd07a37d0daf35a2f725898ddda1d8abe3dd0968fe9e137d3da47449c36e74ea276a6c3712c",
          "sha256": "0cafed641d0ea26dfd04b15cb18a1915f766b3f2cee5e237b0ceda6666a80f9b",
          "sha1": "b8467a58ac3499410c1c473d0d5e71ad5f0ee4de",
          "md5": "896acec733738fc2fdd50effc19f5eb6"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "core-1.0.0-sources.jar",
          "url": "core-1.0.0-sources.jar",
          "size": 46793,
          "sha512": "85e2f4d5fad1897606845135da93231f4ff35c32ffefeccda55f8b40aaec2a938575ac2b29bd9f98646dcf76ab213132e46d10fdafcbaa3a6d9ecaec969c9d66",
          "sha256": "59f7fdb74d4f0927ea01aaf141ad8cad91d0ebec2a6dcbd8b20a16a231ffeeca",
          "sha1": "18089bcc9133dce3a4938ae95cd89fba476ade27",
          "md5": "7c13011bc93b1eaf2bd280a9bf840c22"
        }
      ]
    }
  ]
}
